name: Append changelog

on:
  push:
    branches:
      - "main"

jobs:

  append-changelog:
    name: APPEND CHANGELOG
    runs-on: ubuntu-latest
    steps: 

      - name: Clone git repo
        run: git clone https://${{ secrets.ACTIONS_ACCESS_TOKEN }}@github.com/arachna-net/sandbox.git .

      - name: Add changes file
        run: | 
          git log $(git describe --tags --abbrev=0)...HEAD | grep -E -i '.*\[(fix|feature|improvement)\] *\[*[A-Za-z]+\-[0-9]+\]* +.+'| while read -r line; do; file=".changes/unreleased/Fix-$(date +%Y%m%d)-$(date +%H%M%S%s).yaml"; touch $file; done
      
      - name: Control
        run: ls .changes/unreleased
      