name: Append changelog

on:
  push:
    branches:
      - "main"

jobs:

  append-changelog:
    name: APPEND CHANGELOG
    runs-on: ubuntu-latest
    steps: 

      - name: Clone git repo
        run: git clone https://${{ secrets.ACTIONS_ACCESS_TOKEN }}@github.com/arachna-net/sandbox.git .

      - name: Add changes file
        run: | 
          results=$(git log $(git describe --tags --abbrev=0)...HEAD | grep -E -i '.*\[(fix|feature|improvement)\] *\[*[A-Za-z]+\-[0-9]+\]* +.+')
          while read -r line
          do
            file=".changes/unreleased/Fix-$(date +%Y%m%d)-$(date +%H%M%S%s).yaml"
            touch $file
            echo "kind: $(sed -E 's/^.*\[(fix|feature|improvement)\] *\[*([A-Za-z]+\-[0-9]+)\]* (.+)$/\1/gi' <<< $line)" >> $file
            echo "body: $(sed -E 's/^.*\[(fix|feature|improvement)\] *\[*([A-Za-z]+\-[0-9]+)\]* (.+)$/\3/gi' <<< $line)" >> $file
            echo "time: $(date +%Y-%m-%dT%H:%M:%S.%6NZ%:z)" >> $file
            echo "custom:" >> $file
            echo "  Issue: $(sed -E 's/^.*\[(fix|feature|improvement)\] *\[*([A-Za-z]+\-[0-9]+)\]* (.+)$/\2/gi' <<< $line)" >> $file
            cat $file
            sleep 1 
          done <<< $results
      
      - name: Install changie
        run: |
          mkdir internal
          cd internal
          wget https://github.com/miniscruff/changie/releases/download/v1.6.1/changie_1.6.1_linux_386.deb
          sudo dpkg -i changie_1.6.1_linux_386.deb
          