name: Accumulate release

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Clone git repo
        run: git clone https://${{ secrets.ACCES_TOKEN }}@github.com/arachna-net/sandbox.git . && ls

#      - name: Get parent branch
#        id: get_parent
#        run: git fetch && echo "::set-output name=parent::$(git log --oneline | cut -f 1 -d' ' | (while read commit ; do other_branches=$(git branch --contains $commit | egrep -v '^\* '); if [ -n "${other_branches}" ] ; then echo -e "${other_branches}" && break; fi; done;) | xargs)"
#
#      - name: Check parent branch
#        run: ${{ steps.get_parent.outputs.parent }} && if [ ${{ steps.get_parent.outputs.parent }} = "origin/whitelabel/base" ]; then echo "Is derived from main"; else echo "Is not derived from main" && exit 1; fi;
