name: Accumulate release

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Use git
        uses: actions/checkout@v2

      - name: Get commit number
        id: parent_branch
        run: echo "::set-output name=parent_branch::$(git show-branch | awk '/\*/' | awk '!/${{ steps.extract_branch.outputs.branch }}/' | head -n1 | sed 's/.*\[\(.*\)\].*/\1/')"
        
      - name: Get parent branch
        run: echo ${{ steps.parent_branch.outputs.parent_branch }}
