name: Accumulate release

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Use git
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Print branch contains
        shell: bash
        run: if [ `git branch main --contains $(git reflog ${{ steps.extract_branch.outputs.branch }} | tail -n 1 | cut -d' ' -f1) | wc -l | sed -e 's/^[[:space:]]*//'` -eq 0 ]; then echo "Branch is not derived from master" && exit 1; else echo "Branch is derived from master"; fi;
