name: Check branch is derived from base

on: [push]
    
jobs:
  pre-checks:
    name: Run pre checks
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Use git
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get parent branch
        id: get_parent
        run: git log --oneline | cut -f 1 -d' ' | (while read commit ; do other_branches="$(git branch --contains $commit | egrep -v '^\* ')"; if [ -n "${other_branches}" ] ; then echo -e "${other_branches}" && break; fi; done;) | xargs
