name: Accumulate release

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Use git
        uses: actions/checkout@v2

      - name: Get commit number
        id: parent_branch
        shell: bash
        run: git show-branch | grep -v $(git rev-parse --abbrev-ref HEAD) | head -n1
