name: Accumulate release

on: [push]
    
jobs:
  pre-checks:
    name: Run pre checks
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Use git
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get parent branch
        run: git fetch && echo $(git show-branch -a | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
  build:
    name: Build app
    runs-on: ubuntu-latest
    needs: [pre-checks]
    steps:
      
      - name: Run build
        run: echo "Building"
